### ISSUE TITLE
/usr/lib/librephotos/bin/librephotos-upgrade error: No module named 'pyvips'

### ISSUE THREAD

**Issue by xifi-kif** [LibrePhotos/librephotos-linux#20]
I'm trying to install in a vm (ubuntu 20.04) in order to test the software, install goes fine (except I had to adjust the install script to git pull the correct backend repository). 
But when I try to create the db as the manual says `/usr/lib/librephotos/bin/librephotos-upgrade` I get this error:

```
root@librephotos:~# /usr/lib/librephotos/bin/librephotos-upgrade

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 24, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 24, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 24, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'

```

**Comment by DjSni** [comment]
you can do a simple pip3 install pyvips
