### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-j59zz3tr/dlib/

### ISSUE THREAD

**Issue by timdonovanuk** [LibrePhotos/librephotos-linux#21]
Followed the instructions exactly but:

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-j59zz3tr/dlib/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 473, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 723, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-j59zz3tr/dlib/
Cloning into 'backend'...
fatal: repository 'https://github.com/LibrePhotos/librephotos/tree/67ea61a79dadff8772fa2e7915239840e45a630c/' not found
-bash: line 11: cd: backend: No such file or directory
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
/usr/bin/python3: No module named spacy
```

**Comment by Seneliux** [comment]
In the script is line
`git clone https://github.com/Seneliux/librephotos.git backend`
I just run this line and backend cloned without issues.
But somehow cloning address is change to this:
`fatal: repository 'https://github.com/LibrePhotos/librephotos/tree/67ea61a79dadff8772fa2e7915239840e45a630c/' not found`
Here is  the problem - wrong path.
I do not know how to resolve.

Temporary workaround:
create new script and run:
```
su - -s $(which bash) librephotos << EOF
git clone https://github.com/Seneliux/librephotos.git backend
cd backend
pip3 install -r requirements.txt
EOF

```
If this worked, try to run all script.
