### ISSUE TITLE
No module named 'pyvips'

### ISSUE THREAD

**Issue by stuieordie** [LibrePhotos/librephotos-linux#32]
Trying to install on a fresh Ubuntu 20.04 server. Edited the variable section of the script, and ran it. Seems like it got most of the way through, compiled vips, downloaded a bunch of node.js packages etc, but then got a module not found exception for pyvips. I manually did a pip install pyvips. The frontend + image-similarity services were running, but backend and worker were not with messages relating to the missing pyvips

There are no password files located in /tmp, so I'm guessing the installation did not finish. 

This is the last section of lines from the installer script
```
+ serve@13.0.2
added 48 packages from 20 contributors in 33.361s

82 packages are looking for funding
  run `npm fund` for details

Created symlink /etc/systemd/system/multi-user.target.wants/librephotos-frontend.service → /etc/systemd/system/librephotos-frontend.service.

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 22, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 22, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/lib/librephotos/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/librephotos/backend/api/models/__init__.py", line 1, in <module>
    from api.models.album_auto import AlbumAuto
  File "/usr/lib/librephotos/backend/api/models/album_auto.py", line 6, in <module>
    from api.models.photo import Photo
  File "/usr/lib/librephotos/backend/api/models/photo.py", line 22, in <module>
    from api.thumbnails import (
  File "/usr/lib/librephotos/backend/api/thumbnails.py", line 4, in <module>
    import pyvips
ModuleNotFoundError: No module named 'pyvips'

```

**Comment by derneuere** [comment]
I added it to the installation script! Could you try it again?

**Comment by Seneliux** [comment]
Ubuntu. Only works when compiling libvips.
How to is here:
https://github.com/Seneliux/librephotos-linux/blob/main/install-librephotos.sh
If present, uninstall libvips42 and other vips* packages.

Compiled vips will be placed in /usr/local/include.
After upgrades can get same error. This caused by version mismatch. First must uninstall compiled vips - in the compilation folder run "make uninstall" (good way). Or simply delete /usr/local/include/vips folder (dirty way).

**Comment by Seneliux** [comment]
Also must delete /usr/local/lib/python3.8 - here is older versions.
